language: cpp
compiler:
  - clang
  - gcc

before_script:
  - git diff --cached --name-only --diff-filter=ACMRT ${TRAVIS_COMMIT}~1 | egrep "\.[hc](pp|xx)?$" | xargs -n1 clang-format -style=file -output-replacements-xml > /dev/null
  - if [ $? -ne 1 ]; then echo "please format your code"; exit 1; else exit 0; fi

script:
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_BUILD_TYPE=Debug
  - cmake --build build -- -j2
  - ./hello

